# Generated by Django 6.0 on 2025-12-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comentario_options_remove_comentario_aprobado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('moderar_comentarios', 'Puede moderar comentarios de otros usuarios'), ('ver_comentarios_pendientes', 'Puede ver comentarios pendientes')], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='reaccion',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Reacción', 'verbose_name_plural': 'Reacciones'},
        ),
    ]
