# Generated by Django 6.0 on 2025-12-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_options_usuario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Ususarios'},
        ),
    ]
